### ISSUE TITLE
llama possible ?

### ISSUE THREAD

**Issue by x4080** [huggingface/exporters#39]
from this tweet https://twitter.com/pcuenq/status/1664605575882366980?s=20, it seems possible ?

**Comment by TimYao18** [comment]
This project support llama. You can try it using hugging face version llama model.

**Comment by pcuenca** [comment]
Yes, Llama should work. You can also use https://huggingface.co/spaces/coreml-projects/transformers-to-coreml to run your conversion.

**Comment by x4080** [comment]
cool thanks
