### ISSUE TITLE
`trust_remote_code=True`

### ISSUE THREAD

**Issue by Fihade** [huggingface/exporters#40]
I'm doing exporters with convert tiiuae/falcon-7b-instruct to CoreML Model. 
`python -m exporters.coreml --model=tiiuae/falcon-7b-instruct exported/`

it shows some error to fix it:
![image](https://github.com/huggingface/exporters/assets/24598480/fbabf6b8-16ec-4780-9577-2d632acafe0f)

**Comment by pcuenca** [comment]
Hi @Fihade,

The model is not integrated in `transformers` yet (it requires some custom code to run) so it's still not available in `exporters`. However, there's a converted Core ML version [in the repo](https://huggingface.co/tiiuae/falcon-7b-instruct/tree/main/coreml) that you can test.

**Comment by Fihade** [comment]
Okay, I'm doing this Core ML model in testing. Thanks @pcuenca
